### ISSUE TITLE
Make it an option to allow editing if same public key 

### ISSUE THREAD

**Issue by xdamman** [GoodDollar/gun-appendOnly#2]
### Motivation
I’d love to implement a local exchange trading system. For that, the community needs a public ledger that is append only and that should be immutable. You shouldn’t be able to edit your own past transactions.

### Details
One quick way would be to be able to switch off the edit option if you are the author.

A better more secure way would be to implement a chained list where each new entry references a checksum of the previous one.

**Comment by sirpy** [comment]
@xdamman 
it depends what exactly is your use case.
this plugin is to enable someone to "own" a key in an index ie
`{ key1:data, key2:data}`
for example lets say key1 is the hash of my mobile and I want "data" to be my profile.
so i want to own key1 and be able to control its value.

if you are just looking for immutability gundb already supports that with the hashed index '#'.
gun.get('somepath#').get(hashofdata).put(data)
hashofdata should be something like SEA.work(data) but i'm not exactly sure.
better ask on discord or look at the docs at gun.eco
